name: Android CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v3
        with:
          distribution: "zulu"
          java-version: "12.x"
          cache: "gradle"
      # - name: Create .env file
      #   run: |
      #     echo "${{ secrets.APP_ENV_FILE }}" > .env
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.7.12"
          channel: "stable"
      - run: flutter --version
      - uses: android-actions/setup-android@v2
      - run: sudo apt-get install clang cmake ninja-build pkg-config libgtk-3-dev liblzma-dev -y
      # Decoding base64 key into a file
      # - run: echo "${{ secrets.KEYSTORE2 }}" | base64 --decode > android/app/key.jks
      # # Creating the key.properties file
      # - run: |
      #     echo keyPassword=\${{ secrets.KEY_STORE }} > ${{env.PROPERTIES_PATH}}
      #     echo storePassword=\${{ secrets.KEY_PASSWORD }} >> ${{env.PROPERTIES_PATH}}
      #     echo keyAlias=\${{ secrets.KEY_ALIAS }} >> ${{env.PROPERTIES_PATH}}
      - run: flutter clean
      - run: flutter doctor
      - run: flutter pub get
      - run: flutter build apk --split-per-abi #--release
